import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import PDFDocument from 'pdfkit';
import { formatCityLabel } from './cityReportFilters.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const LOGO_PATH = path.join(__dirname, '../../assets/wastelink-logo.png');

const formatUGX = (amount) => `UGX ${Number(amount || 0).toLocaleString('en-UG')}`;
const formatKg = (kg) => `${Number(kg || 0).toFixed(1)} kg`;

const drawMetricRow = (doc, label, value, y) => {
  doc.font('Helvetica-Bold').fontSize(10).fillColor('#374151').text(label, 50, y, { width: 220 });
  doc.font('Helvetica').fillColor('#111827').text(String(value ?? '—'), 270, y, { width: 275 });
  return y + 18;
};

const drawSectionTitle = (doc, title, y) => {
  doc.font('Helvetica-Bold').fontSize(13).fillColor('#166534').text(title, 50, y);
  return y + 22;
};

export const generateCityReportPdf = (pack) =>
  new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const chunks = [];
    const { meta, executive_summary: summary, undp, sheets } = pack;

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    if (fs.existsSync(LOGO_PATH)) {
      doc.image(LOGO_PATH, 50, 45, { width: 64 });
    }

    doc.font('Helvetica-Bold').fontSize(20).fillColor('#166534').text('WasteLink Uganda', 125, 48);
    doc.font('Helvetica').fontSize(11).fillColor('#6B7280').text('Beta-Tech Labs · City Impact Report', 125, 72);
    doc.font('Helvetica-Bold').fontSize(14).fillColor('#111827').text('UNDP Pilot Summary', 125, 92);

    doc.moveTo(50, 118).lineTo(545, 118).strokeColor('#D1D5DB').lineWidth(1).stroke();

    let y = 132;
    y = drawMetricRow(doc, 'Pilot city', meta.city_label, y);
    y = drawMetricRow(doc, 'Reporting period', `${meta.reporting_period_start} to ${meta.reporting_period_end}`, y);
    y = drawMetricRow(
      doc,
      'Divisions',
      (summary.pilot_divisions || undp.pilot_divisions || []).join(', ') || '—',
      y
    );

    y += 8;
    y = drawSectionTitle(doc, 'Key metrics', y);
    y = drawMetricRow(doc, 'Registered pickers (period)', summary.registered_pickers, y);
    y = drawMetricRow(doc, 'Women participation', `${summary.women_pickers} (${summary.women_percentage}%)`, y);
    y = drawMetricRow(doc, 'Youth participation', `${summary.youth_pickers} (${summary.youth_percentage}%)`, y);
    y = drawMetricRow(doc, 'Active collection points', summary.active_collection_points, y);
    y = drawMetricRow(doc, 'Verified waste logs', summary.verified_logs, y);
    y = drawMetricRow(doc, 'Verified waste total', `${formatKg(summary.total_verified_kg)} (${summary.verified_waste_tonnes} t)`, y);
    y = drawMetricRow(doc, 'Estimated kg (logged)', formatKg(summary.total_estimated_kg), y);
    y = drawMetricRow(doc, 'Pending / unverified kg', formatKg(summary.pending_unverified_kg), y);
    y = drawMetricRow(doc, 'Rejected estimated kg', formatKg(summary.rejected_estimated_kg), y);
    y = drawMetricRow(doc, 'Picker earnings created', formatUGX(summary.confirmed_earnings), y);
    y = drawMetricRow(doc, 'Paid earnings', formatUGX(summary.paid_earnings), y);
    y = drawMetricRow(doc, 'Withdrawals processed', `${summary.withdrawal_count} · ${formatUGX(summary.withdrawal_success_amount)}`, y);

    y += 8;
    y = drawSectionTitle(doc, 'Collection point summary (top 5)', y);
    const topPoints = (sheets.waste_by_collection_point || []).slice(0, 5);
    if (topPoints.length === 0) {
      y = drawMetricRow(doc, 'No collection point activity', '—', y);
    } else {
      topPoints.forEach((point) => {
        y = drawMetricRow(
          doc,
          point.collection_point_name,
          `${formatKg(point.verified_kg)} verified · ${point.verified_logs} jobs · ${formatUGX(point.total_earnings)}`,
          y
        );
      });
    }

    y += 8;
    y = drawSectionTitle(doc, 'UNDP impact narrative', y);
    doc.font('Helvetica').fontSize(10).fillColor('#374151').text(undp.narrative, 50, y, {
      width: 495,
      align: 'justify',
      lineGap: 3,
    });

    doc
      .font('Helvetica')
      .fontSize(8)
      .fillColor('#9CA3AF')
      .text(
        'Generated by WasteLink for municipal and partner reporting. Full working data is available in the Excel workbook export.',
        50,
        760,
        { width: 495, align: 'center' }
      );

    doc.end();
  }).then((buffer) => {
    const slugCity = formatCityLabel(pack.meta.city).replace(/\s+/g, '-');
    const periodSlug =
      pack.meta.report_month || `${pack.meta.reporting_period_start}_${pack.meta.reporting_period_end}`;
    return {
      buffer,
      filename: `WasteLink-${slugCity}-Summary-${periodSlug}.pdf`,
    };
  });
